# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Andover Entreprenuership Forum
email: test-email@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Do you have an idea to change education at AHS? Make it a reality! The Andover Entrepreneurship Forum is a competition to reinvent education.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

process:
  - title: Think
    description: What problem do you want to solve?
    icon: fas fa-lightbulb

  - title: Design
    description: How are you going to solve it?
    icon: fas fa-pencil-ruler

  - title: Submit
    description: Tell us your idea!
    icon: fa fa-paper-plane

  - title: Present
    description: Share your project!
    icon: fab fa-slideshare

timeline:
  - date: January 7<sup>th</sup>, 2019
    title: Challenge Launch
    image: img/icon/rocket.png
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

  - date: February 15<sup>th</sup>, 2019
    title: First Round Pitches Due
    image: img/icon/calendar.png
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

  - date: Marth 5<sup>th</sup>, 2019
    title: First Round Winners Announced
    image: img/icon/award.png
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

  - date: April 9<sup>th</sup>, 2019
    title: Second Round Plan and Pitches Due
    image: img/icon/calendar.png
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

  - date: April 16<sup>th</sup>, 2019
    title: Second Round Winners Announced
    image: img/icon/medal.png
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

  - date: April 23<sup>rd</sup>, 2019
    title: Final Plans and Final Pitches Due
    image: img/icon/calendar.png
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

  - date: May 3<sup>rd</sup>, 2019
    title: Finalists Events
    image: img/icon/trophy.png
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"


exclude: [.idea]